# ~/.streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
maxUploadSize = 200

[global]
showWarningOnDirectExecution = false
